node {
   def commit_id
   stage('step a') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'NodeJS') {
       sh 'cd basics && npm install --only=dev'
       sh 'cd basics && npm test'
     }
   }
   stage('docker build/push') {
     docker.withRegistry('https://index.docker.io/v1/', '	rotemshalev') {
       def app = docker.build("rotemshalev/docker-nodejs-demo:${commit_id}", '.').push()
     }
   }
   stage('docker run') {
     sh label: '', script: '''docker rm docker_test
      docker run --rm -tid --name docker_test -p 3000 yanivomc/docker-nodejs-demo:latest
      docker kill docker_test
      
      '''
     }
   }

